/*
 * Copyright 2016-2020, Intel Corporation
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in
 *       the documentation and/or other materials provided with the
 *       distribution.
 *
 *     * Neither the name of the copyright holder nor the names of its
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * patcher.c -- patching a library
 *
 * Jumping from the subject library:
 *
 *     /--------------------------\
 *     |               subject.so |
 *     |                          |
 *     |  jmp to_trampoline_table |  patched by activate_patches()
 *  /->|   |                      |
 *  |  \___|______________________/
 *  |      |
 *  |  /---|--------------------------\
 *  |  | movabs %r11, wrapper_address | jmp generated by activate_patches()
 *  |  | jmp *%r11                    | This allows subject.so and
 *  |  |   |                          | libsyscall_intercept.so to be farther
 *  |  \___|__________________________/ than 2 gigabytes from each other
 *  |      |
 *  |  /---|-----------------------------\
 *  |  |   |  libsyscall_intercept.so    |
 *  |  |   |                             |
 *  |  | /-|--------------------------\  |
 *  |  | | |  static unsigned char    |  |
 *  |  | | |  asm_wrapper_space[]     |  |
 *  |  | | |    in BSS                |  | wrapper routine
 *  |  | | |                          |  | generated into asm_wrapper_space
 *  |  | | |                          |  | by create_wrapper()
 *  |  | |wrapper routine             |  |
 *  |  | |calls C hook function  ----------> intercept_routine in intercept.c
 *  |  | |movabs %r11, return_address |  |
 *  |  | |jmp *%r11                   |  |
 *  |  | \_|__________________________/  |
 *  |  \___|_____________________________/
 *  |      |
 *  \______/
 *
 */

#include "intercept.h"
#include "intercept_util.h"
#include "intercept_log.h"

#include <assert.h>
#include <stdint.h>
#include <syscall.h>
#include <sys/mman.h>
#include <string.h>

#include <stdio.h>

/* The size of a trampoline jump, 64-bit address loading process into a register
 * (which requires 14 instructions to encode directly in machine code) + JALR.
 * These are preceeded and succeeded by storing and restoring of tmp registers
 * used for the creation of the absolute jump. We can't clobber them since two
 * instructions that were placed before the original ecall still must be
 * executed.
 */
enum { TRAMPOLINE_SIZE = 23 * 4 };

static void create_wrapper(struct patch_desc *patch, unsigned char **dst);
static void create_load_uint64t_into_t0(uint8_t *code, uint64_t value);

/*
 * create_absolute_jump(from, to)
 *
 */
static unsigned char *
create_absolute_jump(unsigned char *from, void *to)
{
	uint32_t *instructions = (uint32_t *)from;
	instructions[0] = 0xff010113; // addi sp, sp, -16
	instructions[1] = 0x00613023; // sd t1, 0(sp)
	instructions[2] = 0x00713423; // sd t2, 8(sp)
	instructions[3] = 0x01c13823; // sd t3, 16(sp)
	instructions[9] = 0x7ffff337; // lui t1, 0x7ffff
	instructions[10] = 0x7ff06393; // ori t2, zero, 0x7ff
	instructions[11] = 0x00139393; // slli t2, t2, 1
	instructions[12] = 0x0013e393; // ori t2, t2, 1
	instructions[13] = 0x00736333; // or t1, t1, t2
	instructions[14] = 0x00131313; // slli t1, t1, 1
	instructions[15] = 0x00136313; // ori t1, t1, 1
	instructions[16] = 0x006e7e33; // and t3, t3, t1
	instructions[17] = 0x01c2e2b3; // or t0, t0, t3
	instructions[18] = 0x00013303; // ld t1, 0(sp)
	instructions[19] = 0x00813383; // ld t2, 8(sp)
	instructions[20] = 0x01013e03; // ld t3, 16(sp)
	instructions[21] = 0x01010113; // addi sp, sp, 16
	instructions[22] = 0x00028067; // jalr zero, t0, 0
	create_load_uint64t_into_t0(instructions + 4,(uint64_t)to); // writes 5 instructions starting from instructions[4]
	return instructions + 23;
}

/*
 * create_jump(opcode, from, to)
 * Create a 5 byte jmp/call instruction jumping to address to, by overwriting
 * code starting at address from.
 */
void
create_jump(unsigned char opcode, unsigned char *from, void *to)
{
	/*
	 * The operand is the difference between the
	 * instruction pointer pointing to the instruction
	 * just after the call, and the to address.
	 * Thus RIP seen by the call instruction is from + 5
	 */
	ptrdiff_t delta = ((unsigned char *)to) - (from + JUMP_INS_SIZE);

	if (delta > ((ptrdiff_t)INT32_MAX) || delta < ((ptrdiff_t)INT32_MIN))
		xabort("create_jump distance check");

	int32_t delta32 = (int32_t)delta;
	unsigned char *d = (unsigned char *)&delta32;

	from[0] = opcode;
	from[1] = d[0];
	from[2] = d[1];
	from[3] = d[2];
	from[4] = d[3];
}

/*
 * check_trampoline_usage -
 * Make sure the trampoline table allocated at the beginning of patching has
 * enough space for all trampolines. This just aborts the process if the
 * allocate space does not seem to be enough, but it can be fairly easy
 * to implement more allocation here if such need would arise.
 */
static void
check_trampoline_usage(const struct intercept_desc *desc)
{
	if (!desc->uses_trampoline_table)
		return;

	/*
	 * We might actually not have enough space for creating
	 * more trampolines.
	 */

	size_t used = (size_t)(desc->next_trampoline - desc->trampoline_table);

	if (used + TRAMPOLINE_SIZE >= desc->trampoline_table_size)
		xabort("trampoline space not enough");
}

/*
 * is_nop_in_range - checks if NOP is sufficiently close to address, to be
 * reachable by a jmp having a 8 bit displacement.
 */
static bool
is_nop_in_range(unsigned char *address, const struct range *nop)
{
	/*
	 * Planning to put a 5 byte jump starting at the third byte
	 * of the nop instruction. The syscall should jump to this
	 * trampoline jump.
	 */
	unsigned char *dst = nop->address + 2;
	/*
	 * Planning to put a two byte jump in the place of the syscall
	 * instruction, that is going to jump relative to the value of
	 * RIP during execution, which points to the next instruction,
	 * at address + 2.
	 */
	unsigned char *src = address + 2;

	/*
	 * How far can this short jump instruction jump, considering
	 * the one byte singed displacement?
	 */
	unsigned char *reach_min = src - 128;
	unsigned char *reach_max = src + 127;

	/*
	 * Can a two byte jump reach the proposed destination?
	 * I.e.: is dst in the [reach_min, reach_max] range?
	 */
	return reach_min <= dst && dst <= reach_max;
}

/*
 * is_copiable_before_syscall
 * checks if an instruction found before a syscall instruction
 * can be copied (and thus overwritten).
 */
static bool
is_copiable_before_syscall(struct intercept_disasm_result ins)
{
	if (!ins.is_set)
		return false;

	return !(ins.has_ip_relative_opr ||
	    ins.is_call ||
	    ins.is_rel_jump ||
	    ins.is_jump ||
	    ins.is_ret ||
	    ins.is_endbr ||
	    ins.is_syscall);
}

/*
 * is_copiable_after_syscall
 * checks if an instruction found after a syscall instruction
 * can be copied (and thus overwritten).
 *
 * Notice: we allow the copy of ret instructions.
 */
static bool
is_copiable_after_syscall(struct intercept_disasm_result ins)
{
	if (!ins.is_set)
		return false;

	return !(ins.has_ip_relative_opr ||
	    ins.is_call ||
	    ins.is_rel_jump ||
	    ins.is_jump ||
	    ins.is_endbr ||
	    ins.is_syscall ||
			ins.uses_ra);
}


/*
 * check_surrounding_instructions
 * Sets up the following members in a patch_desc, based on
 * instruction being relocateable or not:
 * uses_prev_ins ; uses_prev_ins_2 ; uses_next_ins
 */
static void
check_surrounding_instructions(struct intercept_desc *desc,
				struct patch_desc *patch)
{
	patch->uses_prev_ins = (is_copiable_before_syscall(patch->preceding_ins) &&
	    !is_overwritable_nop(&patch->preceding_ins) &&
	    !has_jump(desc, patch->syscall_addr));

	if (patch->uses_prev_ins) {
		patch->uses_prev_ins_2 = (patch->uses_prev_ins &&
		    is_copiable_before_syscall(patch->preceding_ins_2) &&
		    !is_overwritable_nop(&patch->preceding_ins_2) &&
		    !has_jump(desc, patch->syscall_addr - patch->preceding_ins.length));
	} else {
		patch->uses_prev_ins_2 = false;
	}

	patch->uses_next_ins = (is_copiable_after_syscall(patch->following_ins) &&
	    !is_overwritable_nop(&patch->following_ins) &&
	    !has_jump(desc, patch->syscall_addr + ECALL_INS_SIZE));
}

/*
 * create_patch_wrappers - create the custom assembly wrappers
 * around each syscall to be intercepted. Well, actually, the
 * function create_wrapper does that, so perhaps this function
 * deserves a better name.
 * What this function actually does, is figure out how to create
 * a jump instruction in libc ( which bytes to overwrite ).
 * If it successfully finds suitable bytes for hotpatching,
 * then it determines the exact bytes to overwrite, and the exact
 * address for jumping back to libc.
 *
 * This is all based on the information collected by the routine
 * find_syscalls, which does the disassembling, finding jump destinations,
 * finding padding bytes, etc..
 */
void
create_patch_wrappers(struct intercept_desc *desc, unsigned char **dst)
{
	size_t next_nop_i = 0;

	for (unsigned patch_i = 0; patch_i < desc->count; ++patch_i) {
		struct patch_desc *patch = desc->items + patch_i;
		debug_dump("patching %s:0x%lx\n", desc->path,
				patch->syscall_addr - desc->base_addr);

			/*
			 * No padding space is available, so check the
			 * instructions surrounding the syscall instruction.
			 * If they can be relocated, then they can be
			 * overwritten. Of course some instructions depend
			 * on the value of the RIP register, these can not
			 * be relocated.
			 */

			check_surrounding_instructions(desc, patch);

			/*
			 * Count the number of overwritable bytes
			 * in the variable length.
			 * Sum up the bytes that can be overwritten.
			 * The 4 bytes of the ecall instruction can
			 * be overwritten definitely, so length starts
			 * as ECALL_INS_SIZE ( 4 bytes ).
			 */
			unsigned length = ECALL_INS_SIZE;

			patch->dst_jmp_patch = patch->syscall_addr;

			/*
			 * If the preceding instruction is relocatable,
			 * add its length. Also, the the instruction right
			 * before that.
			 */
			if (patch->uses_prev_ins) {
				length += patch->preceding_ins.length;
				patch->dst_jmp_patch -=
				    patch->preceding_ins.length;

				if (patch->uses_prev_ins_2) {
					length += patch->preceding_ins_2.length;
					patch->dst_jmp_patch -=
					    patch->preceding_ins_2.length;
				}
			}

			/*
			 * If the following instruction is relocatable,
			 * add its length. This also affects the return address.
			 * Normally, the library would return to libc after
			 * handling the syscall by jumping to instruction
			 * right after the syscall. But if that instruction
			 * is overwritten, the returning jump must jump to
			 * the instruction after it.
			 */
			if (patch->uses_next_ins) {
				length += patch->following_ins.length;

				/*
				 * Address of the syscall instruction
				 * plus 2 bytes
				 * plus the length of the following instruction
				 *
				 * adds up to:
				 *
				 * the address of the second instruction after
				 * the syscall.
				 */
				patch->return_address = patch->syscall_addr +
				    ECALL_INS_SIZE +
				    patch->following_ins.length;
			}

			/*
			 * If the length is at least 16, then a jump instruction
			 * with a 32 bit displacement can fit.
			 *
			 * Otherwise give up
			 */
			if (length < JUMP_INS_SIZE) {
				char buffer[0x1000];

				int l = snprintf(buffer, sizeof(buffer),
					"unintercepted syscall at: %s 0x%lx\n",
					desc->path,
					patch->syscall_offset);

				intercept_log(buffer, (size_t)l);
				xabort("not enough space for patching"
				    " around syscal");
			}

		mark_jump(desc, patch->return_address);

		create_wrapper(patch, dst);
	}
}

/*
 * Referencing symbols defined in intercept_template.s
 */
extern unsigned char intercept_asm_wrapper_tmpl[];
extern unsigned char intercept_asm_wrapper_tmpl_end;
extern unsigned char intercept_asm_wrapper_patch_desc_addr;
extern unsigned char intercept_asm_wrapper_wrapper_level1_addr;
extern unsigned char intercept_wrapper;

size_t asm_wrapper_tmpl_size;
static ptrdiff_t o_patch_desc_addr;
static ptrdiff_t o_wrapper_level1_addr;

bool intercept_routine_must_save_ymm = false; // temporarily hardcoded

/*
 * init_patcher
 * Some variables need to be initialized before patching.
 * This routine must be called once before patching any library.
 */
void
init_patcher(void)
{
	unsigned char *begin = &intercept_asm_wrapper_tmpl[0];

	assert(&intercept_asm_wrapper_tmpl_end > begin);
	assert(&intercept_asm_wrapper_patch_desc_addr > begin);
	assert(&intercept_asm_wrapper_wrapper_level1_addr > begin);
	assert(&intercept_asm_wrapper_patch_desc_addr <
		&intercept_asm_wrapper_tmpl_end);
	assert(&intercept_asm_wrapper_wrapper_level1_addr <
		&intercept_asm_wrapper_tmpl_end);

	asm_wrapper_tmpl_size =
		(size_t)(&intercept_asm_wrapper_tmpl_end - begin);
	o_patch_desc_addr = &intercept_asm_wrapper_patch_desc_addr - begin;
	o_wrapper_level1_addr =
		&intercept_asm_wrapper_wrapper_level1_addr - begin;
}


/*
 * create_ret_from_template
 * Write a RET instruction (encoded as JALR) to return to patch->return_address.
 * This is possible as long patch->return_address is saved to ra in the first
 * place when jumping to trampoline when intercepting the system call. This is
 * not explicitly written at the end of intercept_template.S since the fourth
 * overwritten instruction has to be relocated before RET.
 */
static unsigned char *
create_ret_from_template(unsigned char *code)
{
	*((uint32_t *)code) = 0x00008067; // jalr zero, ra, 0
	return code + 4;
}

/*
 * create_load_uint64t_into_t0
 * Generates the first 5 instructions (LUI,ADDI,SLLI,LUI,ADDI) of a convoluted
 * 14 instructions sequence that assign a 64 bit constant to a register.
 * See intercept_template.S for the following 9 at
 * intercept_asm_wrapper_patch_desc_addr (an equal sequence is placed at
 * intercept_asm_wrapper_wrapper_level1_addr as well).
 */
static void
create_load_uint64t_into_t0(uint8_t *code, uint64_t value)
{

	uint32_t *instructions = (uint32_t *)code;
	uint32_t upper_32 = (value & 0xffffffff00000000) >> 32;
	uint32_t lower_32 = (uint32_t)value;

	uint32_t lui_imm_field = upper_32 & 0xfffff000;
  uint32_t addi_imm_field = 0;
  if (upper_32 % 4096 != 0) {
    addi_imm_field = upper_32 - lui_imm_field;
    if (addi_imm_field > 2047) {
      lui_imm_field += 4096;
      addi_imm_field = -(4096 - addi_imm_field);
    }
  }

	instructions[0] = 0x000002b7 | lui_imm_field; // lui t0, 0x.....
  instructions[1] = 0x00028293 | (addi_imm_field << 20); // addi t0, t0, 0x...
  instructions[2] = 0x02029293; // slli t0, t0, 32 // could ditch this line as long its placeholder in intercept_template.S isn't different at all

	lui_imm_field = lower_32 & 0xfffff000;
	addi_imm_field = 0;
	if (lower_32 % 4096 != 0) {
		addi_imm_field = lower_32 - lui_imm_field;
		if (addi_imm_field > 2047) {
			lui_imm_field += 4096;
			addi_imm_field = -(4096 - addi_imm_field);
		}
	}

	instructions[3] = 0x00000e37 | lui_imm_field; // lui t3, 0x.....
  instructions[4] = 0x000e0e13 | (addi_imm_field << 20); // addi t3, t3, 0x...

}

/*
 * relocate_instruction
 * Places an instruction equivalent to `ins` to the memory location at `dst`.
 * Only handles instructions that can be copied verbatim, and some LEA
 * instructions.
 */
static unsigned char *
relocate_instruction(unsigned char *dst,
			const struct intercept_disasm_result *ins)
{
		memcpy(dst, ins->address, ins->length);
		return dst + ins->length;
}

/*
 * create_wrapper
 * Generates an assembly wrapper. Copies the template written in
 * intercept_template.s, and generates the instructions specific
 * to a particular syscall into the new copy.
 * After this wrapper is created, a syscall can be replaced with a
 * jump to this wrapper, and wrapper is going to call dest_routine
 * (actually only after a call to mprotect_asm_wrappers).
 */
static void
create_wrapper(struct patch_desc *patch, unsigned char **dst)
{
	/* Create a new copy of the template */
	patch->asm_wrapper = *dst;
	uint32_t *instructions = (uint32_t *)(*dst);

	/* Copy the previous instruction(s) */
	if (patch->uses_prev_ins) {
		if (patch->uses_prev_ins_2) {
			*((uint32_t *)(*dst)) = 0x00813283; // ld t0, 8(sp)
			*dst += 4;
			*((uint32_t *)(*dst)) = 0x01010113; // addi sp, sp, 16
			*dst += 4;
			*dst = relocate_instruction(*dst, &patch->preceding_ins_2);
		}
		*dst = relocate_instruction(*dst, &patch->preceding_ins);
	}

	memcpy(*dst, intercept_asm_wrapper_tmpl, asm_wrapper_tmpl_size);
	create_load_uint64t_into_t0(*dst + o_patch_desc_addr, (uintptr_t)patch); // why the uintptr_t cast? What if the address is not representable on 32 bit?
	create_load_uint64t_into_t0(*dst + o_wrapper_level1_addr,
				(uintptr_t)&intercept_wrapper);
	*dst += asm_wrapper_tmpl_size;

	/* Copy the following instruction */
	if (patch->uses_next_ins)
		*dst = relocate_instruction(*dst, &patch->following_ins);

	// *dst = create_absolute_jump(*dst, patch->return_address); // since ra is updated with patch->return_address by JALR when jumping to trampoline, writing RET is enough
	*dst = create_ret_from_template(*dst);
}

/*
 * create_j(from, to)
 * Create a 4 byte JAL instruction jumping to address to, by overwriting
 * code starting at address from, if trampoline displacement is within + or -
 * 1 MiB. Otherwise create a 2 instructions sequence (LUI + JALR) which allows
 * to reach trampoline if its displacement is within -2 GiB or JALR_MAX_OFFSET,
 * which is (+2 GiB - 2050 Bytes).
 */
void
create_j(unsigned char *from, void *to)
{
	/*
	 * The operand is the difference between the
	 * instruction pointer pointing to the instruction
	 * just after the call, and the to address.
	 */
	ptrdiff_t delta = ((unsigned char *)to) - from;
	uint32_t *instructions = (uint32_t)from;
	uint32_t nop = 0x00000013; // nop instruction
	debug_dump("%p: svc -> b %ld\t# %p\n", from, delta, to);

	const ptrdiff_t JAL_OFFSET = 1 << 20;
	const ptrdiff_t JALR_MAX_OFFSET = 2147481598; // ((2^31-1)-4095)+(2^11-1) == 0x7ffff000 + 0x7ff
	const ptrdiff_t JALR_MIN_OFFSET = -2147483648; // (-2^31) == -0x80000000

	if ((delta & 0x1) != 0) {

		xabort("create_j misaligned instruction fetch exception");

	} else if ((delta <= JAL_OFFSET-2) || (delta >= -JAL_OFFSET)) {
		/* delta can be encoded in a single jal instruction */

		/* halving offset value, since RISC-V doubles the immediate value of jal */
		delta >>= 1;

		/* extracting 20 bits to be encoded in jal instruction */
		uint32_t tmp = (uint32_t) delta & 0x000fffff;
		uint32_t jal = 0x000000ef; /* jal instruction with offset = 0 and rd = ra */
		jal |= ((tmp & 0x3ff) << 21); /* shifting imm[9:0] into jal[30:21] */
		jal |= ((tmp & 0x400) << 10); /* shifting imm[10] into jal[20] */
		jal |= ((tmp & 0x7f800) << 1); /* shifting imm[18:11] into jal[19:12] */
		jal |= ((tmp & 0x80000) << 12); /* shifting imm[19] into jal[31] */

		instructions[0] = jal;
		instructions[1] = nop;
		instructions[2] = nop;
		instructions[3] = nop;

	} else if (delta <= JALR_MAX_OFFSET || delta >= JALR_MIN_OFFSET) {

		uint32_t lui = 0x000002b7; // encoding t0 as rd
		uint32_t jalr = 0x000280e7; // encoding ra as rd and t0 as rs1
		uint32_t jalr_imm_field = 0;
    uint32_t lui_imm_field = (uint32_t)delta & 0xfffff000; // offset[31:12]

		/*
		 * if the offset is not a multiple of 4096 the 12 least significant bits
		 * of its value must be set by adding the correct immediate value contained
		 * in jalr imm field to the rs1 value which is set by lui instruction
		 * preceding jalr
		 */
		if ((uint32_t)delta % 4096 != 0) {
      jalr_imm_field = (uint32_t)delta - lui_imm_field;
      if (jalr_imm_field > 2046) {
        lui_imm_field += 4096;
        jalr_imm_field = -(4096 - jalr_imm_field);
      }
    }
    lui |= lui_imm_field;
    jalr |= (jalr_imm_field << 20);

		instructions[0] = 0xff010113; // addi sp, sp, -16
		instructions[1] = 0x00513423; // sd t0, 8(sp)
		instructions[2] = lui; // lui t0, 0x.....
		instructions[3] = jalr; // jalr ra, t0, 0x...

	} else {
		xabort("create_j distance check");
	}
}

/*
 * activate_patches()
 * Loop over all the patches, and and overwrite each syscall.
 */
void
activate_patches(struct intercept_desc *desc)
{
	unsigned char *first_page;
	size_t size;

	if (desc->count == 0)
		return;

	first_page = round_down_address(desc->text_start);
	size = (size_t)(desc->text_end - first_page);

	mprotect_no_intercept(first_page, size,
	    PROT_READ | PROT_WRITE | PROT_EXEC,
	    "mprotect PROT_READ | PROT_WRITE | PROT_EXEC");

	for (unsigned i = 0; i < desc->count; ++i) {
		const struct patch_desc *patch = desc->items + i;

		if (patch->dst_jmp_patch < desc->text_start ||
		    patch->dst_jmp_patch > desc->text_end)
			xabort("dst_jmp_patch outside text");

		/*
		 * The dst_jmp_patch pointer contains the address where
		 * the actual jump instruction escaping the patched text
		 * segment should be written.
		 * This is either at the place of the original syscall
		 * instruction, or at some usable padding space close to
		 * it (an overwritable NOP instruction).
		 */

		if (desc->uses_trampoline_table) {
			/*
			 * First jump to the trampoline table, which
			 * should be in a 2 gigabyte range. From there,
			 * jump to the asm_wrapper.
			 */
			check_trampoline_usage(desc);

			/* jump - escape the text segment */
			create_j(patch->dst_jmp_patch, desc->next_trampoline);

			/* jump - escape the 2 GB range of the text segment */
			desc->next_trampoline = create_absolute_jump(
				desc->next_trampoline, patch->asm_wrapper);
		} else {
			create_j(patch->dst_jmp_patch, patch->asm_wrapper);
		}

	}

	mprotect_no_intercept(first_page, size,
	    PROT_READ | PROT_EXEC,
	    "mprotect PROT_READ | PROT_EXEC");
}
